
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('birds').del()
    .then(function () {
      // Inserts seed entries
      return knex('birds').insert([
        { bird_id: 1, name: 'Tui', info: 'Tui are unique to New Zealand and belong to the honey-eater family which means that they feed mainly on nectar from the flowers of native plants.\n \n Tui are found throughout New Zealand.', image: '/images/tui.jpg', number: 0, category: 'notThreatened', status: 'Not Threatened', found: 'false' },
        { bird_id: 2, name: 'Kererū', info: 'These big birds like to eat fruit, leaves, twigs and shoots and can eat so much that they get too full and fall out of trees.\n \n  These birds are found all over New Zealand.', image: '/images/kereru.jpg', number: 0, category: 'notThreatened', status: 'Not Threatened', found: 'false' },
        { bird_id: 3, name: 'Pīwakawaka', info: 'Spot these friendly birds by their large tail.\n \n Also known as fantail, these birds build their nests with small materials woven with cobwebs.\n \n They live all over New Zealand, even in the Chatham Islands.', image: '/images/piwakawaka.jpg', number: 0, category: 'notThreatened', status: 'Not Threatened', found: 'false' },
        { bird_id: 4, name: 'Ruru', info: 'Ruru are heard at dusk and throughout the night and they are named after their haunting call.\n \n  Ruru are found throughout New Zealand and in Maori tradition they are seen as watchful guardians of the forest.', image: '/images/ruru.jpg', number: 0, category: 'notThreatened', status: 'Not Threatened', found: 'false' },
        { bird_id: 5, name: 'Kōtare', info: 'Kōtare, also known as sacred kingfisher.\n \n  They live both around the sea, where they feed on small crabs and fish, as well as inland, where what they feed on includes worms, weta, spiders, mice and even small birds!', image: '/images/kotare.jpg', number: 0, category: 'notThreatened', status: 'Not Threatened', found: 'false' },
        { bird_id: 6, name: 'Tōrea Pango', info: 'Tōrea Pango, also known as variable oystercatcher, are found on shorelines around New Zealand.\n \n They really like sandy dunes and you don’t usually see them too far from the coast, where they eat shellfish.', image: '/images/toreapango.jpg', number: 0, category: 'atRisk', status: 'Recovering', found: 'false' },
        { bird_id: 7, name: 'Kakīānau', info: 'Kakīānau, also known as black swan, are native to New Zealand.\n \n They became extinct after the first human settlement of New Zealand but were reintroduced from Australia in the 1860s.', image: '/images/kakianau.jpg', number: 0, category: 'notThreatened', status: 'Not Threatened', found: 'false' },
        { bird_id: 8, name: 'Rosella', info: 'Rosella were introduced from Australia and you can usually hear them coming with their noisy chatter and alarm calls.\n \n They like to eat seeds as well as fruit and leaves.', image: '/images/rosella.jpg', number: 0, category: 'notThreatened', status: 'Introduced and Naturalised', found: 'false' },
        { bird_id: 9, name: 'Quail', info: 'Quail like to eat seeds, fruit and leaves.\n \n They are found throughout most of New Zealand on the scrubby edges of rivers, forests, roads and rural gardens.', image: '/images/californiaquail.jpg', number: 0, category: 'notThreatened', status: 'Introduced and Naturalised', found: 'false' },
        { bird_id: 10, name: 'Thrush', info: 'Thrush like to usually eat from the ground, feeding on spiders, snails, slugs and worms but they also like to eat small berries.\n \n They live all over New Zealand up until around 800m above sea level.', image: '/images/thrush.jpg', number: 0, category: 'notThreatened', status: 'Introduced and Naturalised', found: 'false' },
        { bird_id: 11, name: 'Kakapo', info: 'The Kakapo is the only parrot which cannot fly.\n \n It lives in grassland, scrubland and coastal regions of New Zealand, but is now so rare they can only be seen on protected offshore islands.', image: '/images/kakapo.jpg', number: 0, category: 'threatened', status: 'Nationally Critical', found: 'false' },
        { bird_id: 12, name: 'Kea', info: 'The kea is a parrot and like all parrots it has 4 toes on each foot – two that point forward and two that point backward (zygodactyl).', image: '/images/kea.JPG', number: 0, category: 'threatened', status: 'Nationally Endangered', found: 'false' },
        { bird_id: 13, name: 'Takahe', info: 'The Takahē is a flightless bird indigenous to New Zealand and belonging to the rail family.', image: '/images/takahe.jpg', number: 0, category: 'threatened', status: 'Nationally Vulnerable', found: 'false' },
        { bird_id: 14, name: 'Banded Rail', info: 'Banded rail are rarely seen, as they are well-camouflaged and remain under the cover of wetland vegetation, although their footprints are often seen.', image: '/images/bandedrail.JPG', number: 0, category: 'atRisk', status: 'Declining', found: 'false' },
        { bird_id: 15, name: 'Fairy Prion', info: 'Slightly smaller than a red-billed gull, fairy prions are very similar in appearance to the five other prion species: blue-grey and black above, and white below, with blue bill and legs.', image: '/images/fairyprion.jpg', number: 0, category: 'atRisk', status: 'Relict' , found: 'false'},
        { bird_id: 16, name: 'Black Shag', info: 'This large, mainly black shag is often seen individually or in small groups roosting on rocky headlands, in trees or on artificial structures.\n \n It usually forages alone. ' , image: '/images/blackshag.JPG', number: 0, category: 'atRisk', status: 'Naturally Uncommon', found: 'false' },
        { bird_id: 17, name: 'Hoiho', info: 'The largest of the penguins breeding on the New Zealand mainland, the yellow-eyed penguin has become a flagship species for nature-based tourism in the southern South Island.', image: '/images/hoiho.jpg', number: 0, category: 'threatened', status: 'Nationally Endangered', found: 'false' },
        { bird_id: 18, name: 'Toroa', info: 'Otherwise known as the northern royal albatross, these birds have a 3m wingspan and fly an estimated 190,000km a year.', image: '/images/toroa.jpg', number: 0, category: 'atRisk', status: 'Naturally Uncommon', found: 'false' },
        { bird_id: 19, name: 'Pīhoihoi', info: 'The New Zealand pipit is a small brown-and-white songbird that resembles a lark, but has longer legs, and walks rather than hops.', image: '/images/Pipit.jpg', number: 0, category: 'atRisk', status: 'Naturally Uncommon', found: 'false' },
        { bird_id: 20, name: 'Tawaki', info: 'Fiordland crested penguins are endemic to New Zealand, breeding in small colonies on inaccessible headlands and islets along the shores of south-western South Island and Stewart Island. ', image: '/images/Tawaki.jpg', number: 0, category: 'threatened', status: 'Nationally Vulnerable', found: 'false' }
      
      ]);
    });
};
